# Meta Data for SEO

## Homepage
title = "SOSEMTCC"
titleSeparator = "-"
titleAddition = "Documentation guide for our club"
description = "Documentation for everything around SOSEMTCC"

## Open Graph + Twitter Cards
# images = ["doks.png"]
# twitterSite = "henkverlinde"
# twitterCreator = "henkverlinde"
# facebookAuthor = "verlinde.henk"
# facebookPublisher = "verlinde.henk"
# ogLocale = "en_US"

# ## JSON-LD
# schemaType = "Organization"
# schemaLogo = "logo-doks.png"
# schemaTwitter = "https://twitter.com/henkverlinde"
# schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
# schemaGitHub = "https://github.com/h-enk"
# schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Copyright SOSEMTCC"

# Alert
# alert = false
# alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/c-m-hunt/sosemtcc-docs"
editPage = false
